CREATE TABLE IF NOT EXISTS PRODUCT2 (
PRO_ID TEXT PRIMARY KEY,
PRO_NAME TEXT,
PRO_PRICE REAL,
PRO_COM TEXT
);
 
INSERT INTO PRODUCT2(PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM) VALUES
('1', 'Smartphone', 699.99, 'Apple'),
('2', 'Laptop', 999.99, 'Dell'),
('3', 'Smartwatch', 199.99, 'Samsung'),
('4', 'Tablet', 399.99, 'Lenovo'),
('5', 'Headphones', 149.99, 'Sony'),
('6', 'Gaming Console', 499.99, 'Microsoft'),
('7', 'Bluetooth Speaker', 89.99, 'JBL'),
('8', 'Camera', 1299.99, 'Canon'),
('9', 'Monitor', 249.99, 'LG'),
('10', 'TV', 799.99, 'Samsung');

SELECT * FROM PRODUCT1;
SELECT MIN(PRO_PRICE) FROM PRODUCT2;
SELECT MAX(PRO_PRICE) FROM PRODUCT2;
SELECT PRO_NAME, PRO_PRICE
FROM PRODUCT2
WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT2);
SELECT PRO_NAME, PRO_PRICE
FROM 1
WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT2);