CREATE TABLE IF NOT EXISTS STUDENT (
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDERSS TEXT,
PHONE TEXT,
AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDERSS, PHONE, AGE) VALUES

('1', 'RAM', 'DELHI', '*******', 18),
('2', 'SAM', 'GURGAON', '*******', 20),
('3', 'SURESH', 'ROHTAK', '*******', 18),
('4', 'SHAM', 'DELHI', '*******', 20),
('5', 'HARSH', 'GURGAON', '*******', 18);


SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDERSS = 'DELHI';
